"""Stable quant model and feature constants."""

PREDICTION_HORIZON = 5
ROUND_TRIP_COST = 0.00585
ENTRY_THRESHOLD = 0.60
MARKET_FEATURES = [
    "MARKET_RET_1", "MARKET_RET_5", "MARKET_RET_20", "MARKET_VOL_20",
    "ETF50_RET_5", "STOCK_VS_MARKET_5",
]
OPTION_FEATURES = [
    "OPTION_IV_LEVEL", "OPTION_IV_CHG_1", "OPTION_IV_CHG_5",
    "OPTION_IV_TERM_9D_3M", "OPTION_DATA_MISSING",
]
DATA_QUALITY_FEATURES = ["DATA_PRICE_DIFF_PCT", "DATA_PRICE_WARNING"]
PRICE_DIFF_WARNING_THRESHOLD = 0.02
MODEL_FEATURES = [
    "MA_5", "MA20", "RET_1", "RET_5", "RET_20", "RSI", "Volat",
    "RANGE_PCT", "VOL_RATIO", "VOL_CHG", "INST_NET_RATIO", "MARGIN_CHG",
    "SHORT_CHG", "MACD_OSC", "K", "D",
] + MARKET_FEATURES + OPTION_FEATURES + DATA_QUALITY_FEATURES
